apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ofo-argo-nfs-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: ofo-argo-nfs-pv
  storageClassName: ""