apiVersion: v1
kind: Pod
metadata:
  name: nfs-client-pod4
  namespace: argo
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: nfs-volume
      mountPath: /workdir
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: ofo-argo-nfs-pvc