apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: automate-metashape-workflow-
spec:
  serviceAccountName: argo
  entrypoint: main
  volumes:
  - name: ofo-share-argo
    persistentVolumeClaim:
      claimName: ofo-argo-nfs-pvc

  templates:
    - name: main
      steps:
        - - name: determine-datasets
            template: determine-datasets
        - - name: process-items
            template: process-item
            arguments:
              parameters:
              - name: dataset-name
                value: "{{item}}" # Why is this called "item"?
            withParam: "{{steps.determine-datasets.outputs.result}}"

    - name: determine-datasets
      container:
        image: ghcr.io/open-forest-observatory/argo-toy-workflow
        volumeMounts:
        - name: ofo-share-argo
          mountPath: /workdir
        command: ["python"]
        args: ["./step1.py"]

    - name: process-item
      inputs:
        parameters:
        - name: dataset-name
      dag:
        tasks:
          - name: double-number
            template: double-number
            arguments:
              parameters:
                - name: dataset-name-to-double # Being verbose with parameter name to clarify its purpose and origin
                  value: "{{inputs.parameters.dataset-name}}"
          - name: subtract-number
            dependencies: [double-number]
            template: subtract-number
            arguments:
              parameters:
                - name: dataset-name-to-subtract # Being verbose with parameter name to clarify its purpose and origin
                  value: "{{tasks.double-number.outputs.result}}"
          - name: divide-number
            dependencies: [subtract-number]
            template: divide-number
            arguments:
              parameters:
                - name: dataset-name-to-divide # Being verbose with parameter name to clarify its purpose and origin
                  value: "{{tasks.subtract-number.outputs.result}}"

    - name: double-number
      inputs:
        parameters:
        - name: dataset-name-to-double
      container:
        image: ghcr.io/open-forest-observatory/argo-toy-workflow
        volumeMounts:
        - name: ofo-share-argo
          mountPath: /workdir
        command: ["python"]
        args: ["./step2.py", "{{inputs.parameters.dataset-name-to-double}}"]
        resources:
          limits:
            cpu: "1000m"
          requests:
            cpu: "1000m"

    - name: subtract-number
      inputs:
        parameters:
        - name: dataset-name-to-subtract
      container:
        image: ghcr.io/open-forest-observatory/argo-toy-workflow
        volumeMounts:
        - name: ofo-share-argo
          mountPath: /workdir
        command: ["python"]
        args: ["./step3.py", "{{inputs.parameters.dataset-name-to-subtract}}"]
        resources:
          limits:
            cpu: "1000m"
          requests:
            cpu: "1000m"
    
    - name: divide-number
      inputs:
        parameters:
        - name: dataset-name-to-divide
      container:
        image: ghcr.io/open-forest-observatory/argo-toy-workflow:aa_test
        volumeMounts:
        - name: ofo-share-argo
          mountPath: /workdir
        command: ["python"]
        args: ["./step4.py", "{{inputs.parameters.dataset-name-to-divide}}"]
        resources:
          limits:
            cpu: "1000m"
          requests:
            cpu: "1000m"

